# Generated by Django 5.1.6 on 2025-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cca2', models.CharField(max_length=30)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('population', models.IntegerField()),
                ('timezone', models.CharField(max_length=200)),
                ('flag_png', models.URLField()),
            ],
        ),
    ]
