# Generated by Django 5.1.6 on 2025-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('top_level_domain', models.JSONField()),
                ('alpha2_code', models.CharField(max_length=20)),
                ('alpha3_code', models.CharField(max_length=20)),
                ('calling_codes', models.JSONField()),
                ('capital', models.CharField(max_length=100)),
                ('alt_spellings', models.JSONField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
