# Generated by Django 5.1.6 on 2025-02-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='flag_png',
            new_name='flag',
        ),
    ]
